Faster texlive check

diff --git a/bin/pkg-add b/bin/pkg-add
--- a/bin/pkg-add
+++ b/bin/pkg-add
@@ -8,14 +8,14 @@ SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 if "$SCRIPT_DIR/pkg-missing" "$@"; then
   sudo pacman -S --noconfirm --needed "$@" || exit 1
-fi
 
-for pkg in "$@"; do
-  # Secondary check to handle states where pacman doesn't register an error.
-  if "$SCRIPT_DIR/pkg-missing" "$pkg"; then
-    echo -e "\033[31mError: Package '$pkg' did not install\033[0m" >&2
-    exit 1
-  fi
-done
+  for pkg in "$@"; do
+    # Secondary check to handle states where pacman doesn't register an error.
+    if "$SCRIPT_DIR/pkg-missing" "$pkg"; then
+      echo -e "\033[31mError: Package '$pkg' did not install\033[0m" >&2
+      exit 1
+    fi
+  done
+fi
 
 exit 0
